### PR TITLE
fix products

### PR DESCRIPTION
**Pull request by nikivazou**

### CODE REVIEW

**Comment by nikivazou** [comment]
@vikraman this passes locally. Maybe it is not using the proper version of Liquid Haskell?

**Comment by vikraman** [comment]
444bce99 is in ucsd-progsys/liquidhaskell#840.
Should it be 7ad2935f instead (from ucsd-progsys/liquidhaskell#839) ?

**Comment by nikivazou** [comment]
No, #840 contains #839.

**Comment by nikivazou** [comment]
It is indeed using #840 for the built?

**Comment by vikraman** [comment]
It is using https://github.com/ucsd-progsys/liquidhaskell/pull/840/commits/444bce9952b8af96bb3e954f1e785095f3c86bfa based on the sha1 you used.

**Comment by vikraman** [comment]
https://github.com/ucsd-progsys/liquidhaskell/pull/840/commits/78b4e18331ce69b232534e7b5b382ca566230a43 would be the right one to use, I can also try it out locally.

**Comment by vikraman** [comment]
``` patch
diff --git i/Dockerfile w/Dockerfile
index f7dda5f..371e85d 100644
--- i/Dockerfile
+++ w/Dockerfile
@@ -6,8 +6,9 @@ RUN git clone --recursive https://github.com/ucsd-progsys/liquidhaskell.git /opt
 WORKDIR /opt/liquidhaskell

 # "develop" branch
-ENV LIQUID_SHA 444bce9952b8af96bb3e954f1e785095f3c86bfa
-RUN git checkout ${LIQUID_SHA} && \
+ENV LIQUID_SHA 78b4e18331ce69b232534e7b5b382ca566230a43
+RUN git fetch --all && \
+    git checkout ${LIQUID_SHA} && \
     git submodule update --init --recursive && \
     stack install --local-bin-path=/usr/local/bin \
           liquiddesugar liquid-fixpoint prover liquidhaskell

```

**Comment by nikivazou** [comment]
BTW, this branch proved the wrapper theorems we discussed yesterday for datatypes. No idea how to prove them for newtypes. I opened an issue in LH for suggestions https://github.com/ucsd-progsys/liquidhaskell/issues/841

**Comment by vikraman** [comment]
Thank you!

**Pull request merged**
