### PR TITLE
Nat with verified eq data type

### PR DESCRIPTION
**Pull request by nikivazou**
This works with my Liquid Haskell pull request https://github.com/ucsd-progsys/liquidhaskell/pull/836 (to be merged soon.)

### CODE REVIEW

**Comment by nikivazou** [comment]
Of course tests fail, @vikraman can I link the tests to a Liquid Haskell commit?

**Comment by vikraman** [comment]
Yes, you could change LIQUID_SHA in the Dockerfile to 5acfe16.

**Comment by vikraman** [comment]
I tried it out locally and everything works. Thanks for fixing this!

**Comment by nikivazou** [comment]
No problem! 

BTW, implementation-wise is there anything else that I should fix/edit in Liquid Haskell?

**Comment by vikraman** [comment]
With this fix, we can put VerifiedEq (with laws) and instances in the same module, but we still need things to work across modules. But that's not a blocker right now.

**Pull request merged**
